export const FETCH_ALL_EMPLOYEES_REQUEST = 'FETCH_ALL_EMPLOYEES_REQUEST';
export const FETCH_ALL_EMPLOYEES_SUCCESS = 'FETCH_ALL_EMPLOYEES_SUCCESS';
export const FETCH_ALL_EMPLOYEES_FAILURE = 'FETCH_ALL_EMPLOYEES_FAILURE';

export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAILURE = 'DELETE_EMPLOYEE_FAILURE';

export const CREATE_EMPLOYEE_REQUEST = 'CREATE_EMPLOYEE_REQUEST';
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const CREATE_EMPLOYEE_FAILURE = 'CREATE_EMPLOYEE_FAILURE';

export const FETCH_EMPLOYEE_REQUEST = 'FETCH_EMPLOYEE_REQUEST';
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_FAILURE = 'FETCH_EMPLOYEE_FAILURE';

export const UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_FAILURE = 'UPDATE_EMPLOYEE_FAILURE';

export const FETCH_EMPLOYEE_FINANCIAL_REPORT_REQUEST = 'FETCH_EMPLOYEE_FINANCIAL_REPORT_REQUEST';
export const FETCH_EMPLOYEE_FINANCIAL_REPORT_SUCCESS = 'FETCH_EMPLOYEE_FINANCIAL_REPORT_SUCCESS';
export const FETCH_EMPLOYEE_FINANCIAL_REPORT_FAILURE = 'FETCH_EMPLOYEE_FINANCIAL_REPORT_FAILURE';

// Employee Payment
export const CREATE_EMPLOYEE_PAYMENT_REQUEST = 'CREATE_EMPLOYEE_PAYMENT_REQUEST';
export const CREATE_EMPLOYEE_PAYMENT_SUCCESS = 'CREATE_EMPLOYEE_PAYMENT_SUCCESS';
export const CREATE_EMPLOYEE_PAYMENT_FAILURE = 'CREATE_EMPLOYEE_PAYMENT_FAILURE';

export const DELETE_EMPLOYEE_PAYMENT_REQUEST = 'DELETE_EMPLOYEE_PAYMENT_REQUEST';
export const DELETE_EMPLOYEE_PAYMENT_SUCCESS = 'DELETE_EMPLOYEE_PAYMENT_SUCCESS';
export const DELETE_EMPLOYEE_PAYMENT_FAILURE = 'DELETE_EMPLOYEE_PAYMENT_FAILURE';

export const FETCH_EMPLOYEE_PAYMENT_REQUEST = 'FETCH_EMPLOYEE_PAYMENT_REQUEST';
export const FETCH_EMPLOYEE_PAYMENT_SUCCESS = 'FETCH_EMPLOYEE_PAYMENT_SUCCESS';
export const FETCH_EMPLOYEE_PAYMENT_FAILURE = 'FETCH_EMPLOYEE_PAYMENT_FAILURE';

export const UPDATE_EMPLOYEE_PAYMENT_REQUEST = 'UPDATE_EMPLOYEE_PAYMENT_REQUEST';
export const UPDATE_EMPLOYEE_PAYMENT_SUCCESS = 'UPDATE_EMPLOYEE_PAYMENT_SUCCESS';
export const UPDATE_EMPLOYEE_PAYMENT_FAILURE = 'UPDATE_EMPLOYEE_PAYMENT_FAILURE';

// Employee Vacation
export const CREATE_EMPLOYEE_VACATION_REQUEST = 'CREATE_EMPLOYEE_VACATION_REQUEST';
export const CREATE_EMPLOYEE_VACATION_SUCCESS = 'CREATE_EMPLOYEE_VACATION_SUCCESS';
export const CREATE_EMPLOYEE_VACATION_FAILURE = 'CREATE_EMPLOYEE_VACATION_FAILURE';

export const DELETE_EMPLOYEE_VACATION_REQUEST = 'DELETE_EMPLOYEE_VACATION_REQUEST';
export const DELETE_EMPLOYEE_VACATION_SUCCESS = 'DELETE_EMPLOYEE_VACATION_SUCCESS';
export const DELETE_EMPLOYEE_VACATION_FAILURE = 'DELETE_EMPLOYEE_VACATION_FAILURE';

export const FETCH_EMPLOYEE_VACATION_REQUEST = 'FETCH_EMPLOYEE_VACATION_REQUEST';
export const FETCH_EMPLOYEE_VACATION_SUCCESS = 'FETCH_EMPLOYEE_VACATION_SUCCESS';
export const FETCH_EMPLOYEE_VACATION_FAILURE = 'FETCH_EMPLOYEE_VACATION_FAILURE';

export const UPDATE_EMPLOYEE_VACATION_REQUEST = 'UPDATE_EMPLOYEE_VACATION_REQUEST';
export const UPDATE_EMPLOYEE_VACATION_SUCCESS = 'UPDATE_EMPLOYEE_VACATION_SUCCESS';
export const UPDATE_EMPLOYEE_VACATION_FAILURE = 'UPDATE_EMPLOYEE_VACATION_FAILURE';
