export const FETCH_ALL_EMPLOYEE_PAYMENTS_REQUEST = 'FETCH_ALL_EMPLOYEE_PAYMENTS_REQUEST';
export const FETCH_ALL_EMPLOYEE_PAYMENTS_SUCCESS = 'FETCH_ALL_EMPLOYEE_PAYMENTS_SUCCESS';
export const FETCH_ALL_EMPLOYEE_PAYMENTS_FAILURE = 'FETCH_ALL_EMPLOYEE_PAYMENTS_FAILURE';

export const DELETE_EMPLOYEE_PAYMENT_REQUEST = 'DELETE_EMPLOYEE_PAYMENT_REQUEST';
export const DELETE_EMPLOYEE_PAYMENT_SUCCESS = 'DELETE_EMPLOYEE_PAYMENT_SUCCESS';
export const DELETE_EMPLOYEE_PAYMENT_FAILURE = 'DELETE_EMPLOYEE_PAYMENT_FAILURE';

export const CREATE_EMPLOYEE_PAYMENT_REQUEST = 'CREATE_EMPLOYEE_PAYMENT_REQUEST';
export const CREATE_EMPLOYEE_PAYMENT_SUCCESS = 'CREATE_EMPLOYEE_PAYMENT_SUCCESS';
export const CREATE_EMPLOYEE_PAYMENT_FAILURE = 'CREATE_EMPLOYEE_PAYMENT_FAILURE';

export const FETCH_EMPLOYEE_PAYMENT_REQUEST = 'FETCH_EMPLOYEE_PAYMENT_REQUEST';
export const FETCH_EMPLOYEE_PAYMENT_SUCCESS = 'FETCH_EMPLOYEE_PAYMENT_SUCCESS';
export const FETCH_EMPLOYEE_PAYMENT_FAILURE = 'FETCH_EMPLOYEE_PAYMENT_FAILURE';

export const UPDATE_EMPLOYEE_PAYMENT_REQUEST = 'UPDATE_EMPLOYEE_PAYMENT_REQUEST';
export const UPDATE_EMPLOYEE_PAYMENT_SUCCESS = 'UPDATE_EMPLOYEE_PAYMENT_SUCCESS';
export const UPDATE_EMPLOYEE_PAYMENT_FAILURE = 'UPDATE_EMPLOYEE_PAYMENT_FAILURE';
